# Generated by Django 3.2.5 on 2021-08-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuhc', '0004_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='uploded_at',
        ),
    ]
