# Generated by Django 3.2.5 on 2021-08-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhc', '0005_auto_20210831_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ImageField(default=4, upload_to=''),
            preserve_default=False,
        ),
    ]
