# Generated by Django 3.2.5 on 2021-08-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhc', '0005_auto_20210831_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image', models.CharField()),
                ('image', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
    ]
