# Generated by Django 3.2.5 on 2021-08-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhc', '0006_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id_image',
            field=models.CharField(max_length=50),
        ),
    ]
