# Generated by Django 3.2.5 on 2021-08-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhc', '0008_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
