# Generated by Django 3.2.5 on 2021-08-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhc', '0009_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='static/assets/img/uploads/'),
        ),
    ]
