# Generated by Django 3.2.5 on 2021-09-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhc', '0010_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf',
            field=models.FileField(default=4, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
