# Generated by Django 3.2.5 on 2021-09-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhc', '0011_auto_20210901_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
