# Generated by Django 3.2.5 on 2021-09-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhc', '0012_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
