# Generated by Django 3.2.7 on 2021-09-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhc', '0013_alter_article_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf',
            field=models.FileField(upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
