# Generated by Django 3.2.7 on 2021-09-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhc', '0014_auto_20210904_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
